#!/usr/bin/env python

import json
import os
import sys

repos_path = sys.argv[1]
if os.path.exists(repos_path):
    repositories = json.load(open(repos_path))
else:
    repositories = {}
repositories.update(json.load(sys.stdin))
with os.fdopen(os.open(repos_path, os.O_CREAT | os.O_WRONLY, 0o600), 'w') as f:
    json.dump(repositories, f, indent=2)
print (json.dumps(repositories, indent=2))